### ISSUE TITLE
Ubuntu 14.04 with Oracle Java 8 initialization error

### ISSUE THREAD

**Issue by alex4321** [zheludkovm/LinuxJavaFixes#10]
I have downloaded it's in /opt/ with next command:

    cd /opt
    sudo git clone https://github.com/zheludkovm/LinuxJavaFixes

And added
   
    java ...
    -javaagent:/opt/LinuxJavaFixes/build/LinuxJavaFixes-1.0.0-SNAPSHOT.jar

to initialization script.

But after it, when I running it I getting

Error opening zip file or JAR manifest missing : /opt/LinuxJavaFixes/build/LinuxJavaFixes-1.0.0-SNAPSHOT.jar 
Error occurred during initialization of VM
agent library failed to init: instrument

But ls write that absolute path is right.
What may be wrong?

**Comment by alex4321** [comment]
Strange, but (after some changes) now I can't reproduce it.

**Comment by wysow** [comment]
@alex4321 can you describe what you changed, I'm currently facing the same problem...

**Comment by wysow** [comment]
@alex4321 ok got it, need to add `/build/` before the name of the jar file, we should update the readme about that right?
