### ISSUE TITLE
Possible NPE in transform

### ISSUE THREAD

**Issue by Mingun** [zheludkovm/LinuxJavaFixes#4]
At line
https://github.com/zheludkovm/LinuxJavaFixes/blob/master/src/main/java/net/x11/patch/XKeysymTransformer.java#L28

`className` may be `NULL` if [ClassLoader.defineClass][1] was invoked with `null` argument for `className`, what is legal.

[1]: http://docs.oracle.com/javase/7/docs/api/java/lang/ClassLoader.html#defineClass%28java.lang.String,%20byte%5B%5D,%20int,%20int%29

**Comment by zheludkovm** [comment]
Add null pointer check
