### ISSUE TITLE
ubuntu 14.04 + webstorm 9

### ISSUE THREAD

**Issue by adarrra** [zheludkovm/LinuxJavaFixes#5]
Hi! I'm not very experienced user...
Ububntu 14.04 + webstorm 9:
I have "webstorm.vmoptions" - if I write here nothing happens
and "webstorm64.vmoptions" - if I write here webstorm dosen't run

I added:  -javaagent:/home/user/Downloads/shortcut_fix/LinuxJavaFixes-1.0.0-SNAPSHOT.jar

**Comment by zheludkovm** [comment]
What version of JDK are you using ?
Can you run webstorm from console and submit log ?

**Comment by zheludkovm** [comment]
Hello, Adara!
I'm sorry, i dont check this mail box often.
Please, try external JDK
download JDK from here
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
download tar.gz version for Linux x64
unpack it and add following first line to webstorm.sh
export JAVA_HOME=<path to unpacked jdk directory>

and then run webstorm.sh from console
if it stil not work - please submit logs to me.

Muchael Zheludkov.
​

**Comment by adarrra** [comment]
Hi! Sorry for very long answering.
So 
 if I write in  "webstorm.vmoptions" I get `Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0`
if I write in  "webstorm64.vmoptions" I get
`_fix/LinuxJavaFixes-1.0.0-SNAPSHOT.jar
Error occurred during initialization of VM
agent library failed to init: instrument
`

**Comment by zheludkovm** [comment]
Hello!
It looks like you have error in your path to
LinuxJavaFixes-1.0.0-SNAPSHOT.jar
can you provide full log ?


Michael Zheludkov.

2015-04-03 14:42 GMT+03:00 Adara <notifications@github.com>:

**Comment by adarrra** [comment]
hmm, that was full...
sorry for my stupidity...
maybe you are right... from where should  path to  LinuxJavaFixes-1.0.0-SNAPSHOT.jar starting? 

~~~adarab@BelayaA:~/Downloads/WebStorm-139.1112/bin$ ./webstorm.sh Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
Error opening zip file or JAR manifest missing : /home/adarab/Downloads/shortcut_fix/LinuxJavaFixes-1.0.0-SNAPSHOT.jar
Error occurred during initialization of VM
agent library failed to init: instrument
~~~

**Comment by zheludkovm** [comment]
Hello, Adara!
You need full path from root (/) when you specify javaagent path
please check directory /home/adarab/Downloads/shortcut_fix/
it contains two jars (LinuxJavaFixes-1.0.0-SNAPSHOT.jar,
javassist-3.12.1.GA.jar) ?

may be jars are corrupted ?
please retry to download jars :
git clone https://github.com/zheludkovm/LinuxJavaFixes.git

Michael Zheludkov

2015-04-06 14:07 GMT+03:00 Adara <notifications@github.com>:

**Comment by adarrra** [comment]
uh, everything works! Maybe files were corrupted... I am not sure. Thank you very much for answers and so cool fix.

**Comment by zheludkovm** [comment]
Woohoo!!!
Ура!!!

2015-04-06 15:33 GMT+03:00 Adara <notifications@github.com>:
