### ISSUE TITLE
elementary OS Freya + PhpStorm 8.0.3 [czech]

### ISSUE THREAD

**Issue by HoBi** [zheludkovm/LinuxJavaFixes#7]
Hi, I have downloaded files from your build and added them to **/home/hobi/.java-fixes/**.

I added `-javaagent:/home/hobi/.java-fixes/LinuxJavaFixes-1.0.0-SNAPSHOT.jar` to the **phpstorm.vmoptions** and **phpstorm64.vmoptions** files.

I use elementary OS, which is based on Ubuntu 14.04 LTS and I use **czech keyboard**.
I have Java 8 installed via `sudo apt-get install oracle-java8-installer` command.

But it doesn't work... It still throws me `unknown keycode 0x0` error. 

Any idea how to fix it? :)

**Comment by zheludkovm** [comment]
Hi!
can you provide console log ?
please run phpstorm.sh manually from console

**Comment by hobi** [comment]
@zheludkovm Unfortunately, I deleted linux, but when I will try linux again, I'll write you!

**Comment by dimuravyev** [comment]
**sh bin/phpstorm.sh**
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
Gtk-Message: Failed to load module "pantheon-filechooser-module"

(java:17385): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:17385): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:17385): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:17385): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:17385): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Gtk-Message: Failed to load module "canberra-gtk-module"
[   3452]   WARN - om.intellij.util.ProfilingUtil - Profiling agent is not enabled. Add -agentlib:yjpagent to idea.vmoptions if necessary to profile IDEA.
```

**Comment by rromanovsky** [comment]
sh ~/Programs/PhpStorm-141.2462/bin/phpstorm.sh 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
Error opening zip file or JAR manifest missing : ~/Programs/PhpStorm-141.2462/bin/LinuxJavaFixes-1.0.0-SNAPSHOT.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Comment by zheludkovm** [comment]
Please specify full path to LinuxJavaFixes-1.0.0-SNAPSHOT.jar file
~ is not working for java agent path
